# Generated by Django 4.1.3 on 2022-11-25 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('birth_certificate', models.ImageField(blank=True, null=True, upload_to='DOB')),
                ('admission_number', models.IntegerField(unique=True)),
                ('parent_name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female'), ('Other', 'other')], max_length=10)),
                ('status', models.CharField(choices=[('Active', 'active'), ('Closed', 'closed')], default='Active', max_length=10)),
                ('batch', models.CharField(choices=[('LKG', 'lkg'), ('UKG', 'ukg'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=10)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.academic_year')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('birth_certificate', models.ImageField(blank=True, null=True, upload_to='DOB')),
                ('admission_number', models.IntegerField(unique=True)),
                ('parent_name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female'), ('Other', 'other')], max_length=10)),
                ('status', models.CharField(choices=[('Active', 'active'), ('Closed', 'closed')], default='Active', max_length=10)),
                ('batch', models.CharField(choices=[('LKG', 'lkg'), ('UKG', 'ukg'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=10)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.academic_year')),
            ],
        ),
    ]
