# Generated by Django 4.1.3 on 2022-11-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='DOB'),
        ),
    ]
